language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_install: bash build_etcd.sh

before_script:
  - composer install

script: vendor/bin/phpunit

notifications:
    on_success: never
    on_failure: always